spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: karusalaanil02@gmail.com
    password: bltqwyrtzsmngxlb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


